ARG BASE_IMAGE=nvcr.io/nvidia/isaac/ros:aarch64-ros2_humble
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3-vcstool build-essential git \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    ros-humble-slam-toolbox \
    ros-humble-robot-state-publisher \
    ros-humble-joint-state-publisher \
    ros-humble-robot-localization \
    ros-humble-xacro \
    ros-humble-tf2-ros \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-controller-manager \
    ros-humble-controller-manager-msgs \
    ros-humble-joy \
    ros-humble-teleop-twist-joy \
    ros-humble-teleop-twist-keyboard \
    ros-humble-rosbag2-storage-mcap \
    ros-humble-rviz2 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && pip3 install moteus

RUN echo 'alias b="cd /workspaces/isaac_ros-dev && colcon build --symlink-install && source install/setup.bash && cd -"' >> /etc/skel/.bashrc
