ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --allow-releaseinfo-change && apt-get install -y \
        git \
        nano \
        swig \
        ros-humble-xacro \
        python3-vcstool \
        build-essential \
        ros-humble-navigation2 \
        ros-humble-nav2-bringup \
        ros-humble-slam-toolbox \
        ros-humble-robot-localization \
        ros-humble-tf2-ros \
        ros-humble-rviz2 \
        ros-humble-rosbag2-storage-mcap \
        ros-humble-foxglove-bridge \
        ros-humble-teleop-twist-keyboard \
        ros-humble-ros2-control \
        # ros-humble-ros2-controllers \
        ros-humble-joint-state-publisher \
        ros-humble-controller-manager \
        ros-humble-controller-manager-msgs \
        ros-humble-robot-state-publisher \
        ros-humble-gazebo-ros-pkgs \
        ros-humble-gazebo-ros2-control \
        ros-humble-isaac-ros-visual-slam \
        ros-humble-isaac-ros-realsense \
        ros-humble-isaac-ros-examples \
        ros-humble-isaac-ros-nvblox \
        ros-humble-pinocchio \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && pip3 install moteus

RUN mkdir -p /usr/local/bin/scripts/entrypoint_additions

COPY additional_entrypoint.sh /usr/local/bin/scripts/entrypoint_additions/additional_entrypoint.sh
RUN chmod +x /usr/local/bin/scripts/entrypoint_additions/additional_entrypoint.sh
