FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y \
    python3-vcstool build-essential git \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    ros-humble-slam-toolbox \
    ros-humble-robot-state-publisher \
    ros-humble-joint-state-publisher \
    ros-humble-robot-localization \
    ros-humble-xacro \
    ros-humble-tf2-ros \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-controller-manager \
    ros-humble-controller-manager-msgs \
    ros-humble-joy \
    ros-humble-teleop-twist-joy \
    ros-humble-teleop-twist-keyboard \
    ros-humble-rosbag2-storage-mcap \
    ros-humble-gazebo-ros2-control \
    ros-humble-rviz2 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /BoxyGo

COPY src/ src/
COPY overlays/ overlays/

RUN bash -lc "source /opt/ros/humble/setup.bash && colcon build --symlink-install"
ENV ROS_DOMAIN_ID=1

CMD ["/bin/bash"]

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc && \
    echo "if [ -f /BoxyGo/install/setup.bash ]; then source /BoxyGo/install/setup.bash; fi" >> /root/.bashrc
