<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="add_sensors" params="parent:=base_link body_length:=0.81 body_height:=0.5">



    <!-- IMU sensor -->
    <link name="imu_link">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
      </inertial>
    </link>
    <joint name="imu_joint" type="fixed">
      <parent link="base_link"/>
      <child link="imu_link"/>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="imu_link">
      <sensor type="imu" name="imu_sensor">
        <always_on>true</always_on>
        <update_rate>60.0</update_rate>
        <imu>
          <noise>
            <angular_velocity>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.001</stddev>
            </angular_velocity>
            <linear_acceleration>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.001</stddev>
            </linear_acceleration>
          </noise>
        </imu>
        <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
          <ros>
            <namespace>/</namespace>
            <remapping>~/out:=imu/data</remapping>
          </ros>
          <frame_name>imu_link</frame_name>
          <orientation>0.01 0 0  0 0.01 0  0 0 0.01</orientation>
          <angular_velocity>0.01 0 0  0 0.01 0  0 0 0.01</angular_velocity>
          <linear_acceleration>999 0 0  0 999 0  0 0 999</linear_acceleration>
        </plugin>
      </sensor>
    </gazebo>

    <!-- footprint-->
    <joint name="base_footprint_joint" type="fixed">
          <parent link="base_link"/>
          <child link="base_footprint"/>
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </joint>

      <link name="base_footprint">
      </link>

    <!-- Kamera -->
    <link name="depth_camera_link">
      <visual>
        <geometry>
          <box size="0.02 0.09 0.03"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.02 0.09 0.03"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="depth_camera_joint" type="fixed">
      <parent link="base_link"/>
      <child link="depth_camera_link"/>
      <origin xyz="${body_length/2 + 0.01} 0 ${body_height/2 - 0.1}" rpy="0 0 0"/>
    </joint>

    <joint name="depth_camera_optical_joint" type="fixed">
      <parent link="depth_camera_link"/>
      <child link="depth_camera_link_optical"/>
      <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/> <!-- -pi/2 in radians -->
    </joint>

    <link name="depth_camera_link_optical"/>

    <gazebo reference="depth_camera_link">
      <sensor name="depth_camera" type="depth">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize> 
        <update_rate>60.0</update_rate>
        <camera>
          <horizontal_fov>1.39626</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>B8G8R8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>10.0</far>
          </clip>
        </camera>
        <plugin name="depth_camera_controller" filename="libgazebo_ros_camera.so">
          <camera_name>depth_camera</camera_name>
          <frame_name>depth_camera_link_optical</frame_name>
          <min_depth>0.1</min_depth>
          <max_depth>100.0</max_depth>
        </plugin>
      </sensor>
    </gazebo>

    <!-- Lidar 2D -->
    <link name="lidar_link">
      <visual>
        <geometry>
          <cylinder length="0.05" radius="0.03"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.05" radius="0.03"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="lidar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="lidar_link"/>
      <origin xyz="${body_length/2 - 0.03} 0 ${body_height/2 + 0.025}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="lidar_link">
      <sensor name="lidar_sensor" type="ray">
        <always_on>true</always_on>
        <update_rate>60.0</update_rate>
        <visualize>false</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1</resolution>
              <min_angle>-3.14159</min_angle>
              <max_angle>3.14159</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.3</min>
            <max>12</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
          <topicName>scan</topicName>
          <ros>
              <argument>~/out:=scan</argument>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
          <frameName>lidar_link</frameName>
        </plugin>
      </sensor>
    </gazebo>

    <gazebo reference="lidar_link">
      <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="depth_camera_link">
      <material>Gazebo/Black</material>
    </gazebo>


  </xacro:macro>
</robot> 
