<?xml version="1.0"?>
<robot name="delivery_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Właściwości -->
  <xacro:property name="body_length" value="0.9"/>
  <xacro:property name="body_width" value="0.5"/>
  <xacro:property name="body_height" value="0.6"/>
  <xacro:property name="wheel_radius" value="0.1016"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_gap" value="0.35"/>
  <xacro:property name="wheel_y_offset" value="${0.5 * body_width + 0.05}"/>
  <xacro:property name="z_offset" value="${-0.5 * body_height - 0.1}"/>
  <xacro:property name="wheel_mass" value="3.0"/>
  <xacro:property name="pkg_path" value="$(find boxygo)"/>

  <!-- Materiały -->
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="white"><color rgba="0.7 0.7 0.7 0.5"/></material>
  <material name="grey"><color rgba="0.5 0.5 0.5 1"/></material>

  <!-- Korpus -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="20"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
  </link>


  <!-- footprint-->
  <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>
  
    <!-- Kamera -->
  <link name="depth_camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="depth_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="depth_camera_link"/>
    <origin xyz="${body_length/2 + 0.025} 0 ${body_height/2 - 0.025 - 0.05}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="depth_camera_link">
    <sensor name="depth_camera_sensor" type="camera">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>30.0</update_rate>
      <camera>
        <horizontal_fov>1.39626</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>10.0</far>
        </clip>
      </camera>
      <plugin name="depth_camera_controller" filename="libgazebo_ros_camera.so">
        <camera_name>depth_camera</camera_name>
        <frame_name>depth_camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

    <!-- Lidar 2D -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${body_length/2 - 0.03} 0 ${body_height/2 + 0.025}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="lidar_link">
    <sensor name="lidar_sensor" type="ray">
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <visualize>true</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>12</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
        <topicName>scan</topicName>
        <ros>
            <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>


  <link name="left_rocker_beam">
    <inertial>
      <mass value="0.8"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="${pkg_path}/meshes/rocker_model.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="${pkg_path}/meshes/rocker_model.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
  </link>

  <joint name="left_rocker_beam_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_rocker_beam"/>
    <origin xyz="-0.175 ${wheel_y_offset} ${z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10.0" velocity="10.0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <link name="right_rocker_beam">
  <inertial>
    <mass value="0.8"/>
    <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
  </inertial>
  <visual>
    <geometry>
      <mesh filename="${pkg_path}/meshes/rocker_model.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 ${math.pi}"/>
    <material name="grey"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="${pkg_path}/meshes/rocker_model.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 ${math.pi}"/>
  </collision>
</link>
<joint name="right_rocker_beam_joint" type="continuous">
  <parent link="base_link"/>
  <child link="right_rocker_beam"/>
  <origin xyz="-0.175 ${-wheel_y_offset} ${z_offset}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <limit effort="10.0" velocity="10.0"/>
  <dynamics damping="0.1" friction="0.1"/>
</joint>

<xacro:macro name="wheel_universal" params="side parent_link wheel_side_sign index x_offset y_offset z_offset">
  <xacro:property name="ixx" value="${(1.0/12.0) * wheel_mass * (3 * wheel_radius**2 + wheel_width**2)}"/>
  <xacro:property name="izz" value="${0.5 * wheel_mass * wheel_radius**2}"/>
  <link name="${side}_wheel_${index}">
    <inertial> 
      <mass value="${wheel_mass}"/>
      <inertia ixx="${ixx}" iyy="${ixx}" izz="${izz}" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="${pkg_path}/meshes/hov_wheel_short_look.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 ${wheel_side_sign * math.pi}"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="${pkg_path}/meshes/hov_wheel_short_colision.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 ${wheel_side_sign * math.pi}"/>
    </collision>
  </link>
  <gazebo reference="${side}_wheel_${index}">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>100000.0</kp>
    <kd>10.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>0.01</maxVel>
  </gazebo>
  <joint name="${side}_wheel_${index}_joint" type="continuous">
    <parent link="${parent_link}"/>
    <child link="${side}_wheel_${index}"/>
    <origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10.0" velocity="10.0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>
  <transmission name="${side}_wheel_${index}_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${side}_wheel_${index}_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="${side}_wheel_${index}_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</xacro:macro>

<!-- Koła LEWE: -->
<!-- 1. Koło przy base_link (lewa strona) -->
<xacro:wheel_universal
    side="left"
    parent_link="base_link"
    wheel_side_sign="0"
    index="1"
    x_offset="${wheel_gap}"
    y_offset="${wheel_y_offset}"
    z_offset="${z_offset}"/>

<!-- 2. Koło przy left_rocker_beam (lewa strona, środek) -->
<xacro:wheel_universal
    side="left"
    parent_link="left_rocker_beam"
    wheel_side_sign="0"
    index="2"
    x_offset="0.175"
    y_offset="0"
    z_offset="0"/>

<!-- 3. Koło przy left_rocker_beam (lewa strona, tył) -->
<xacro:wheel_universal
    side="left"
    parent_link="left_rocker_beam"
    wheel_side_sign="0"
    index="3"
    x_offset="-0.175"
    y_offset="0"
    z_offset="0"/>

<!-- Koła PRAWE: -->
<!-- 1. Koło przy base_link (prawa strona) -->
<xacro:wheel_universal
    side="right"
    parent_link="base_link"
    wheel_side_sign="1"
    index="1"
    x_offset="${wheel_gap}"
    y_offset="-${wheel_y_offset}"
    z_offset="${z_offset}"/>

<!-- 2. Koło przy right_rocker_beam (prawa strona, środek) -->
<xacro:wheel_universal
    side="right"
    parent_link="right_rocker_beam"
    wheel_side_sign="1"
    index="2"
    x_offset="0.175"
    y_offset="0"
    z_offset="0"/>

<!-- 3. Koło przy right_rocker_beam (prawa strona, tył) -->
<xacro:wheel_universal
    side="right"
    parent_link="right_rocker_beam"
    wheel_side_sign="1"
    index="3"
    x_offset="-0.175"
    y_offset="0"
    z_offset="0"/>



  <!-- Gazebo - kolor -->
  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>
  <gazebo reference="left_wheel_1">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="left_wheel_2">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="left_wheel_3">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="right_wheel_1">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="right_wheel_2">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="right_wheel_3">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="depth_camera_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="lidar_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- Plugin ros2_control -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <update_rate>30</update_rate>
      <parameters>${pkg_path}/config/diff_drive_controller_v1.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- ros2_control hardware -->
  <ros2_control name="BoxyGoSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="left_wheel_1_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="left_wheel_2_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="left_wheel_3_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="right_wheel_1_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="right_wheel_2_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="right_wheel_3_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

</robot>