<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="boxyGo">
  <!-- Parametry -->
  <xacro:property name="length"  value="0.4"/>
  <xacro:property name="width"   value="0.3"/>
  <xacro:property name="height"  value="0.2"/>
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_separation" value="0.2"/>

  <!-- Korpus -->
  <link name="base_link">
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual>
      <geometry><box size="${length} ${width} ${height}"/></geometry>
      <material><color rgba="0.2 0.2 0.8 1"/></material>
    </visual>
    <collision>
      <geometry><box size="${length} ${width} ${height}"/></geometry>
    </collision>
  </link>

  <!-- Koła napędowe -->
  <link name="wheel_left"/>
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_left"/>
    <origin xyz="0  ${width/2} 0" rpy="0 0 0"/>
    <axis  xyz="0 1 0"/>
  </joint>

  <link name="wheel_right"/>
  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_right"/>
    <origin xyz="0 -${width/2} 0" rpy="0 0 0"/>
    <axis  xyz="0 1 0"/>
  </joint>

  <!-- LIDAR 2D -->
  <link name="lidar_link"/>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
  </joint>
  <gazebo>
    <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
      <ros>
        <namespace>/</namespace>
        <argument>scan:=/scan</argument>
      </ros>
      <update_rate>10.0</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>36</samples>
            <min_angle>-1.57</min_angle>
            <max_angle>1.57</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>5.0</max>
        </range>
      </ray>
    </plugin>
  </gazebo>

  <!-- Opcjonalnie: IMU, kamera itp. -->
</robot>
