controller_manager:
  ros__parameters:
    update_rate: 60
    diff_cont:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    use_stamped_vel: false
    publish_rate: 60.0
    publish_limited_velocity: true
    base_frame_id: base_link
    odom_frame_id: odometry/filtered # odom
    publish_odometry_tf: false
    left_wheel_names: ["left_wheel_1_joint", "left_wheel_2_joint", "left_wheel_3_joint"]
    right_wheel_names: ["right_wheel_1_joint", "right_wheel_2_joint", "right_wheel_3_joint"]
    wheel_separation: 0.55  # 6_wheel_robot.urdf.xacro 0.657    robot_luksusowy.urdf.xacro 0.55
    wheel_radius: 0.085     # 6_wheel_robot.urdf.xacro 0.1016   robot_luksusowy.urdf.xacro 0.085
    enable_odom_tf: false # był problem z podwójnym publikowaniem tf, więc wyłączyłem

