slam_toolbox:
  ros__parameters:

    # Tryb działania: mapping lub localization
    mode: "localization"

    # Nazwy ramek i tematów
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "/scan"
    odom_topic: "/odometry/filtered"

    # Parametry skanera
    resolution: 0.05
    max_laser_range: 12.0
    min_laser_range: 0.1

    # Podstawowe opcje SLAM
    use_scan_matching: true
    use_scan_barycenter: true
    scan_buffer_length: 1.0
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 10.0
    loop_closure_translation_threshold: 0.2
    loop_closure_rotation_threshold: 0.6

    queue_size: 50

    # Loop closure
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Solver
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Inne opcje
    debug_logging: false
    throttle_scans: 2
    map_update_interval: 0.5
    transform_publish_period: 0.02
    transform_timeout: 0.5
    tf_buffer_duration: 120.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # Matcher penalizacje
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    # Korelacja
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Ekstra
    min_pass_through: 2
    occupancy_threshold: 0.1
